# Generated by Django 4.1 on 2022-09-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['id'], 'verbose_name': 'Дата', 'verbose_name_plural': 'Данные'},
        ),
        migrations.AddField(
            model_name='data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
